enable-magisk-update = false

[YouTube]
build-mode = "apk"
patches-source = "kitadai31/revanced-patches-android6-7"
cli-source = "inotia00/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
version = "17.34.36"
