enable-magisk-update = false

[YouTube]
build-mode = "apk"
patches-source = "kitadai31/revanced-patches-android6-7"
cli-source = "inotia00/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
version = "17.34.36"

[Music]
arch = "arm64-v8a"
version = "8.15.52"
patches-version = "v5.4.0"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
