enable-magisk-update = false

[YouTube]
rv-brand = "rvx-android67"
build-mode = "apk"
patches-source = "kitadai31/revanced-patches-android6-7"
integrations-source = "kitadai31/revanced-integrations"
cli-source = "kitadai31/rvcli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
version = "17.34.36"
